sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t jaskirat1120/docker-react .

script:
  - docker run jaskirat1120/docker-react -e CI=true npm run test -- --coverage